// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package go_micro_service_order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	RequestAllOrder
	ResponseAllOrder
	OrderID
	OrderInfo
	OrderDetail
	ResponseMessage
	RequestPayStatus
	RequestShipStatus
*/
package go_micro_service_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestAllOrder struct {
}

func (m *RequestAllOrder) Reset()                    { *m = RequestAllOrder{} }
func (m *RequestAllOrder) String() string            { return proto.CompactTextString(m) }
func (*RequestAllOrder) ProtoMessage()               {}
func (*RequestAllOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseAllOrder struct {
	OrderInfo []*OrderInfo `protobuf:"bytes,1,rep,name=order_info,json=orderInfo" json:"order_info,omitempty"`
}

func (m *ResponseAllOrder) Reset()                    { *m = ResponseAllOrder{} }
func (m *ResponseAllOrder) String() string            { return proto.CompactTextString(m) }
func (*ResponseAllOrder) ProtoMessage()               {}
func (*ResponseAllOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseAllOrder) GetOrderInfo() []*OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type OrderID struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderID) Reset()                    { *m = OrderID{} }
func (m *OrderID) String() string            { return proto.CompactTextString(m) }
func (*OrderID) ProtoMessage()               {}
func (*OrderID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrderID) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type OrderInfo struct {
	Id          int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PayStatus   int32          `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
	ShipStatus  int32          `protobuf:"varint,3,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
	Price       float64        `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	OrderDetail []*OrderDetail `protobuf:"bytes,5,rep,name=order_detail,json=orderDetail" json:"order_detail,omitempty"`
}

func (m *OrderInfo) Reset()                    { *m = OrderInfo{} }
func (m *OrderInfo) String() string            { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()               {}
func (*OrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OrderInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfo) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

func (m *OrderInfo) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func (m *OrderInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetOrderDetail() []*OrderDetail {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type OrderDetail struct {
	Id            int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ProductId     int64 `protobuf:"varint,2,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductNum    int64 `protobuf:"varint,3,opt,name=product_num,json=productNum" json:"product_num,omitempty"`
	ProductSizeId int64 `protobuf:"varint,4,opt,name=product_size_id,json=productSizeId" json:"product_size_id,omitempty"`
	ProductPrice  int64 `protobuf:"varint,5,opt,name=product_price,json=productPrice" json:"product_price,omitempty"`
	OrderId       int64 `protobuf:"varint,6,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderDetail) Reset()                    { *m = OrderDetail{} }
func (m *OrderDetail) String() string            { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()               {}
func (*OrderDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail) GetProductNum() int64 {
	if m != nil {
		return m.ProductNum
	}
	return 0
}

func (m *OrderDetail) GetProductSizeId() int64 {
	if m != nil {
		return m.ProductSizeId
	}
	return 0
}

func (m *OrderDetail) GetProductPrice() int64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type ResponseMessage struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *ResponseMessage) Reset()                    { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()               {}
func (*ResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResponseMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RequestPayStatus struct {
	OrderId   int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	PayStatus int32 `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
}

func (m *RequestPayStatus) Reset()                    { *m = RequestPayStatus{} }
func (m *RequestPayStatus) String() string            { return proto.CompactTextString(m) }
func (*RequestPayStatus) ProtoMessage()               {}
func (*RequestPayStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RequestPayStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *RequestPayStatus) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

type RequestShipStatus struct {
	OrderId    int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	ShipStatus int32 `protobuf:"varint,2,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
}

func (m *RequestShipStatus) Reset()                    { *m = RequestShipStatus{} }
func (m *RequestShipStatus) String() string            { return proto.CompactTextString(m) }
func (*RequestShipStatus) ProtoMessage()               {}
func (*RequestShipStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestShipStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *RequestShipStatus) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestAllOrder)(nil), "go.micro.service.order.RequestAllOrder")
	proto.RegisterType((*ResponseAllOrder)(nil), "go.micro.service.order.ResponseAllOrder")
	proto.RegisterType((*OrderID)(nil), "go.micro.service.order.OrderID")
	proto.RegisterType((*OrderInfo)(nil), "go.micro.service.order.OrderInfo")
	proto.RegisterType((*OrderDetail)(nil), "go.micro.service.order.OrderDetail")
	proto.RegisterType((*ResponseMessage)(nil), "go.micro.service.order.ResponseMessage")
	proto.RegisterType((*RequestPayStatus)(nil), "go.micro.service.order.RequestPayStatus")
	proto.RegisterType((*RequestShipStatus)(nil), "go.micro.service.order.RequestShipStatus")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0xba, 0xc5, 0xe3, 0x40, 0xda, 0x55, 0x01, 0x13, 0x09, 0x35, 0x6c, 0x10, 0x35,
	0x2f, 0x46, 0x2a, 0x3f, 0xc0, 0xc5, 0xa2, 0x8a, 0x04, 0xb4, 0x72, 0xca, 0x13, 0x42, 0x91, 0x1b,
	0x4f, 0x83, 0x45, 0x9c, 0x35, 0x5e, 0x1b, 0x29, 0xfd, 0x28, 0xde, 0xf9, 0x00, 0xfe, 0xab, 0xf2,
	0xf8, 0x12, 0x37, 0x6a, 0xe2, 0xf4, 0x25, 0x5a, 0x9f, 0x39, 0x73, 0xdb, 0x73, 0x36, 0xf0, 0x34,
	0x8a, 0x45, 0x22, 0xde, 0x88, 0xd8, 0xc7, 0x38, 0xff, 0xb5, 0x09, 0x61, 0x4f, 0xa6, 0xc2, 0x0e,
	0x83, 0x49, 0x2c, 0x6c, 0x89, 0xf1, 0x9f, 0x60, 0x82, 0x36, 0x45, 0xf9, 0x01, 0x74, 0x5d, 0xfc,
	0x9d, 0xa2, 0x4c, 0xde, 0xcf, 0x66, 0x67, 0x04, 0x5d, 0xc0, 0xbe, 0x8b, 0x32, 0x12, 0x73, 0x89,
	0x25, 0xc6, 0xde, 0x01, 0x10, 0x7f, 0x1c, 0xcc, 0xaf, 0x84, 0xa9, 0xf4, 0x55, 0xcb, 0x38, 0x79,
	0x61, 0xdf, 0x5d, 0xd3, 0xa6, 0x94, 0xe1, 0xfc, 0x4a, 0xb8, 0xba, 0x28, 0x8f, 0xfc, 0x25, 0xec,
	0xe5, 0xb8, 0xc3, 0x9e, 0xc1, 0x83, 0xa2, 0x98, 0x6f, 0x2a, 0x7d, 0xc5, 0x52, 0xdd, 0xbd, 0x9c,
	0xe7, 0xf3, 0x7f, 0x0a, 0xe8, 0x55, 0x3a, 0x7b, 0x04, 0xed, 0x8a, 0xd2, 0x0e, 0x7c, 0xf6, 0x1c,
	0x20, 0xf2, 0x16, 0x63, 0x99, 0x78, 0x49, 0x2a, 0xcd, 0x76, 0x5f, 0xb1, 0x34, 0x57, 0x8f, 0xbc,
	0xc5, 0x88, 0x00, 0x76, 0x04, 0x86, 0xfc, 0x19, 0x44, 0x65, 0x5c, 0xa5, 0x38, 0x64, 0x50, 0x41,
	0x38, 0x04, 0x2d, 0x8a, 0x83, 0x09, 0x9a, 0x3b, 0x7d, 0xc5, 0x52, 0xdc, 0xfc, 0x83, 0x7d, 0x82,
	0x4e, 0x3e, 0x8e, 0x8f, 0x89, 0x17, 0xcc, 0x4c, 0x8d, 0xb6, 0x1b, 0x6c, 0xdc, 0xce, 0x21, 0xaa,
	0x6b, 0x88, 0xe5, 0x07, 0xff, 0xaf, 0x80, 0x51, 0x0b, 0xde, 0x39, 0x7d, 0x2c, 0xfc, 0x74, 0x92,
	0x64, 0x8b, 0xb7, 0x09, 0xd7, 0x0b, 0x64, 0xe8, 0x67, 0xd3, 0x97, 0xe1, 0x79, 0x1a, 0xd2, 0xf4,
	0xaa, 0x5b, 0x66, 0x7c, 0x4d, 0x43, 0xf6, 0x0a, 0xba, 0x25, 0x41, 0x06, 0xd7, 0x98, 0x15, 0xd9,
	0x21, 0xd2, 0xc3, 0x02, 0x1e, 0x05, 0xd7, 0x38, 0xf4, 0xd9, 0x00, 0x4a, 0x60, 0x9c, 0x6f, 0xab,
	0x11, 0xab, 0x53, 0x80, 0xe7, 0xb4, 0x74, 0x5d, 0x83, 0xdd, 0xdb, 0x1a, 0x0c, 0x32, 0x4b, 0xe4,
	0xfa, 0x7f, 0x41, 0x29, 0xbd, 0x29, 0xb2, 0x7d, 0x50, 0x43, 0x39, 0xa5, 0x5d, 0x74, 0x37, 0x3b,
	0xf2, 0xcf, 0x99, 0x49, 0xc8, 0x37, 0xe7, 0xd5, 0xfd, 0xaf, 0xd7, 0xb5, 0x41, 0x39, 0x7e, 0x06,
	0x07, 0x45, 0xb5, 0xd1, 0x52, 0xad, 0x0d, 0xe5, 0x56, 0x94, 0x6e, 0xaf, 0x2a, 0x7d, 0xf2, 0x57,
	0x03, 0x2d, 0x77, 0xee, 0x05, 0x74, 0x4e, 0x31, 0xa1, 0xf3, 0x87, 0xc5, 0xd0, 0x61, 0x47, 0x9b,
	0x5d, 0xeb, 0xf4, 0x9a, 0x6d, 0xcd, 0x5b, 0xec, 0x12, 0x8c, 0x53, 0xac, 0x9e, 0x0c, 0x3b, 0x5e,
	0x97, 0xb3, 0xf2, 0xb6, 0x7a, 0xd6, 0x7a, 0xe2, 0xed, 0x17, 0xc7, 0x5b, 0x6c, 0x04, 0xc6, 0xc7,
	0x18, 0xbd, 0x04, 0xf3, 0x1e, 0xcd, 0x73, 0xf5, 0x9a, 0x76, 0xe3, 0x2d, 0xf6, 0x03, 0xba, 0x0e,
	0xce, 0xb0, 0x28, 0xba, 0xdd, 0x8d, 0x1c, 0x37, 0x0d, 0x5d, 0xd8, 0x84, 0xb7, 0xd8, 0x2f, 0x38,
	0xfc, 0x16, 0xf9, 0xe5, 0xcc, 0x4b, 0x6b, 0x58, 0x0d, 0x17, 0x54, 0x31, 0xef, 0xd3, 0x2c, 0x84,
	0xc7, 0xb5, 0x66, 0x35, 0xe7, 0xbc, 0x6e, 0xe8, 0xb6, 0xa4, 0xde, 0xa7, 0xdd, 0x77, 0x30, 0x6a,
	0xed, 0xb6, 0xd1, 0x63, 0xfb, 0xe2, 0x97, 0xbb, 0xf4, 0x37, 0xfd, 0xf6, 0x26, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0xb8, 0x1b, 0x03, 0xc1, 0x05, 0x00, 0x00,
}
